sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_4.json cpu ./profiling/edlenet_1_P_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_4.json gpu ./profiling/edlenet_1_P_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_16_1.json cpu ./profiling/edlenet_1_P_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_16_1.json gpu ./profiling/edlenet_1_P_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_8_1.json cpu ./profiling/edlenet_0_C_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_8_1.json gpu ./profiling/edlenet_0_C_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_2.json cpu ./profiling/edlenet_5_P_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_2.json gpu ./profiling/edlenet_5_P_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_4.json cpu ./profiling/edlenet_5_P_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_4.json gpu ./profiling/edlenet_5_P_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_4.json cpu ./profiling/edlenet_3_P_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_4.json gpu ./profiling/edlenet_3_P_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_4_1.json cpu ./profiling/edlenet_5_P_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_4_1.json gpu ./profiling/edlenet_5_P_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_16_1.json cpu ./profiling/edlenet_6_L_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_16_1.json gpu ./profiling/edlenet_6_L_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_16_1.json cpu ./profiling/edlenet_7_L_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_16_1.json gpu ./profiling/edlenet_7_L_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_4_1.json cpu ./profiling/edlenet_7_L_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_4_1.json gpu ./profiling/edlenet_7_L_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_16_1.json cpu ./profiling/edlenet_0_C_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_16_1.json gpu ./profiling/edlenet_0_C_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_8.json cpu ./profiling/edlenet_3_P_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_8.json gpu ./profiling/edlenet_3_P_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_8_1.json cpu ./profiling/edlenet_4_C_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_8_1.json gpu ./profiling/edlenet_4_C_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_4_1.json cpu ./profiling/edlenet_0_C_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_4_1.json gpu ./profiling/edlenet_0_C_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_4.json cpu ./profiling/edlenet_8_S_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_4.json gpu ./profiling/edlenet_8_S_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_8_1.json cpu ./profiling/edlenet_5_P_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_8_1.json gpu ./profiling/edlenet_5_P_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_8_1.json cpu ./profiling/edlenet_6_L_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_8_1.json gpu ./profiling/edlenet_6_L_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_8.json cpu ./profiling/edlenet_2_C_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_8.json gpu ./profiling/edlenet_2_C_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_8_1.json cpu ./profiling/edlenet_2_C_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_8_1.json gpu ./profiling/edlenet_2_C_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_4.json cpu ./profiling/edlenet_4_C_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_4.json gpu ./profiling/edlenet_4_C_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_2.json cpu ./profiling/edlenet_6_L_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_2.json gpu ./profiling/edlenet_6_L_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_16_1.json cpu ./profiling/edlenet_4_C_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_16_1.json gpu ./profiling/edlenet_4_C_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_16_1.json cpu ./profiling/edlenet_8_S_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_16_1.json gpu ./profiling/edlenet_8_S_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_16.json cpu ./profiling/edlenet_2_C_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_16.json gpu ./profiling/edlenet_2_C_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_2.json cpu ./profiling/edlenet_2_C_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_2.json gpu ./profiling/edlenet_2_C_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_8.json cpu ./profiling/edlenet_0_C_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_8.json gpu ./profiling/edlenet_0_C_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_2.json cpu ./profiling/edlenet_7_L_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_2.json gpu ./profiling/edlenet_7_L_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_2_1.json cpu ./profiling/edlenet_8_S_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_2_1.json gpu ./profiling/edlenet_8_S_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_8.json cpu ./profiling/edlenet_6_L_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_8.json gpu ./profiling/edlenet_6_L_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_8.json cpu ./profiling/edlenet_1_P_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_8.json gpu ./profiling/edlenet_1_P_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_4.json cpu ./profiling/edlenet_7_L_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_4.json gpu ./profiling/edlenet_7_L_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_4_1.json cpu ./profiling/edlenet_1_P_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_4_1.json gpu ./profiling/edlenet_1_P_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_2_1.json cpu ./profiling/edlenet_1_P_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_2_1.json gpu ./profiling/edlenet_1_P_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_2.json cpu ./profiling/edlenet_8_S_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_2.json gpu ./profiling/edlenet_8_S_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_4_1.json cpu ./profiling/edlenet_2_C_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_4_1.json gpu ./profiling/edlenet_2_C_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_16.json cpu ./profiling/edlenet_8_S_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_16.json gpu ./profiling/edlenet_8_S_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_16.json cpu ./profiling/edlenet_5_P_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_16.json gpu ./profiling/edlenet_5_P_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_2.json cpu ./profiling/edlenet_0_C_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_2.json gpu ./profiling/edlenet_0_C_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_16_1.json cpu ./profiling/edlenet_2_C_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_16_1.json gpu ./profiling/edlenet_2_C_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_2_1.json cpu ./profiling/edlenet_7_L_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_2_1.json gpu ./profiling/edlenet_7_L_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_8_1.json cpu ./profiling/edlenet_7_L_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_8_1.json gpu ./profiling/edlenet_7_L_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_16_1.json cpu ./profiling/edlenet_3_P_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_16_1.json gpu ./profiling/edlenet_3_P_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_8_1.json cpu ./profiling/edlenet_8_S_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_8_1.json gpu ./profiling/edlenet_8_S_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_2.json cpu ./profiling/edlenet_1_P_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_2.json gpu ./profiling/edlenet_1_P_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_16.json cpu ./profiling/edlenet_3_P_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_16.json gpu ./profiling/edlenet_3_P_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_4_1.json cpu ./profiling/edlenet_8_S_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_4_1.json gpu ./profiling/edlenet_8_S_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_2_1.json cpu ./profiling/edlenet_6_L_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_2_1.json gpu ./profiling/edlenet_6_L_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_2_1.json cpu ./profiling/edlenet_3_P_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_2_1.json gpu ./profiling/edlenet_3_P_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_2_1.json cpu ./profiling/edlenet_2_C_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_2_1.json gpu ./profiling/edlenet_2_C_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_4_1.json cpu ./profiling/edlenet_4_C_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_4_1.json gpu ./profiling/edlenet_4_C_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_4_1.json cpu ./profiling/edlenet_3_P_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_4_1.json gpu ./profiling/edlenet_3_P_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_16.json cpu ./profiling/edlenet_4_C_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_16.json gpu ./profiling/edlenet_4_C_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_8_1.json cpu ./profiling/edlenet_1_P_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_8_1.json gpu ./profiling/edlenet_1_P_8_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_8.json cpu ./profiling/edlenet_8_S_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_8.json gpu ./profiling/edlenet_8_S_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_16.json cpu ./profiling/edlenet_1_P_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_16.json gpu ./profiling/edlenet_1_P_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_8.json cpu ./profiling/edlenet_5_P_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_8.json gpu ./profiling/edlenet_5_P_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_16.json cpu ./profiling/edlenet_7_L_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_16.json gpu ./profiling/edlenet_7_L_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_8.json cpu ./profiling/edlenet_4_C_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_8.json gpu ./profiling/edlenet_4_C_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_2_1.json cpu ./profiling/edlenet_4_C_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_2_1.json gpu ./profiling/edlenet_4_C_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_4.json cpu ./profiling/edlenet_6_L_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_4.json gpu ./profiling/edlenet_6_L_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_16_1.json cpu ./profiling/edlenet_5_P_16_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_16_1.json gpu ./profiling/edlenet_5_P_16_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_16.json cpu ./profiling/edlenet_0_C_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_16.json gpu ./profiling/edlenet_0_C_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_8.json cpu ./profiling/edlenet_7_L_1_8_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_8.json gpu ./profiling/edlenet_7_L_1_8_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_2_1.json cpu ./profiling/edlenet_5_P_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_2_1.json gpu ./profiling/edlenet_5_P_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_2.json cpu ./profiling/edlenet_3_P_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_2.json gpu ./profiling/edlenet_3_P_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_4.json cpu ./profiling/edlenet_0_C_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_4.json gpu ./profiling/edlenet_0_C_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_2_1.json cpu ./profiling/edlenet_0_C_2_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_2_1.json gpu ./profiling/edlenet_0_C_2_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_4.json cpu ./profiling/edlenet_2_C_1_4_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_4.json gpu ./profiling/edlenet_2_C_1_4_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_4_1.json cpu ./profiling/edlenet_6_L_4_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_4_1.json gpu ./profiling/edlenet_6_L_4_1_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_16.json cpu ./profiling/edlenet_6_L_1_16_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_16.json gpu ./profiling/edlenet_6_L_1_16_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_2.json cpu ./profiling/edlenet_4_C_1_2_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_2.json gpu ./profiling/edlenet_4_C_1_2_gpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_8_1.json cpu ./profiling/edlenet_3_P_8_1_cpu.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_8_1.json gpu ./profiling/edlenet_3_P_8_1_gpu.timing interference
