sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json cpu ./profiling/edlenet_6_L_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_6_L_1_1.json gpu ./profiling/edlenet_6_L_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json cpu ./profiling/edlenet_4_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_4_C_1_1.json gpu ./profiling/edlenet_4_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json cpu ./profiling/edlenet_2_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_2_C_1_1.json gpu ./profiling/edlenet_2_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json cpu ./profiling/edlenet_1_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_1_P_1_1.json gpu ./profiling/edlenet_1_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json cpu ./profiling/edlenet_7_L_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_7_L_1_1.json gpu ./profiling/edlenet_7_L_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json cpu ./profiling/edlenet_5_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_5_P_1_1.json gpu ./profiling/edlenet_5_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json cpu ./profiling/edlenet_0_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_0_C_1_1.json gpu ./profiling/edlenet_0_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json cpu ./profiling/edlenet_3_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_3_P_1_1.json gpu ./profiling/edlenet_3_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json cpu ./profiling/edlenet_8_S_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/edlenet_8_S_1_1.json gpu ./profiling/edlenet_8_S_1_1_gpu_10.timing interference
