sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu_10.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_1.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_2.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_3.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_4.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_5.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_6.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_7.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_8.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_9.timing interference
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu_10.timing interference
