sudo service lightdm stop
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_8.json cpu ./profiling/yololite_0_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_8.json gpu ./profiling/yololite_0_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_4_1.json cpu ./profiling/yololite_3_P_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_4_1.json gpu ./profiling/yololite_3_P_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_2.json cpu ./profiling/yololite_11_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_2.json gpu ./profiling/yololite_11_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_16.json cpu ./profiling/yololite_3_P_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_16.json gpu ./profiling/yololite_3_P_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json cpu ./profiling/yololite_10_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_1.json gpu ./profiling/yololite_10_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_8.json cpu ./profiling/yololite_6_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_8.json gpu ./profiling/yololite_6_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_2_1.json cpu ./profiling/yololite_1_P_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_2_1.json gpu ./profiling/yololite_1_P_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_2.json cpu ./profiling/yololite_4_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_2.json gpu ./profiling/yololite_4_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_8.json cpu ./profiling/yololite_2_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_8.json gpu ./profiling/yololite_2_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_8.json cpu ./profiling/yololite_1_P_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_8.json gpu ./profiling/yololite_1_P_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_8_1.json cpu ./profiling/yololite_3_P_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_8_1.json gpu ./profiling/yololite_3_P_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_2.json cpu ./profiling/yololite_10_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_2.json gpu ./profiling/yololite_10_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_4_1.json cpu ./profiling/yololite_6_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_4_1.json gpu ./profiling/yololite_6_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json cpu ./profiling/yololite_2_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_1.json gpu ./profiling/yololite_2_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_2_1.json cpu ./profiling/yololite_0_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_2_1.json gpu ./profiling/yololite_0_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_16_1.json cpu ./profiling/yololite_1_P_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_16_1.json gpu ./profiling/yololite_1_P_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_16_1.json cpu ./profiling/yololite_4_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_16_1.json gpu ./profiling/yololite_4_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_16.json cpu ./profiling/yololite_2_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_16.json gpu ./profiling/yololite_2_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_4.json cpu ./profiling/yololite_0_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_4.json gpu ./profiling/yololite_0_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_8.json cpu ./profiling/yololite_4_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_8.json gpu ./profiling/yololite_4_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_16.json cpu ./profiling/yololite_4_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_16.json gpu ./profiling/yololite_4_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_2_1.json cpu ./profiling/yololite_11_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_2_1.json gpu ./profiling/yololite_11_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_4.json cpu ./profiling/yololite_10_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_4.json gpu ./profiling/yololite_10_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_8_1.json cpu ./profiling/yololite_10_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_8_1.json gpu ./profiling/yololite_10_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_8_1.json cpu ./profiling/yololite_8_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_8_1.json gpu ./profiling/yololite_8_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json cpu ./profiling/yololite_5_P_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_1.json gpu ./profiling/yololite_5_P_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_4.json cpu ./profiling/yololite_11_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_4.json gpu ./profiling/yololite_11_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_8_1.json cpu ./profiling/yololite_5_P_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_8_1.json gpu ./profiling/yololite_5_P_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_2.json cpu ./profiling/yololite_5_P_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_2.json gpu ./profiling/yololite_5_P_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_4.json cpu ./profiling/yololite_1_P_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_4.json gpu ./profiling/yololite_1_P_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_4.json cpu ./profiling/yololite_2_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_4.json gpu ./profiling/yololite_2_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json cpu ./profiling/yololite_1_P_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_1.json gpu ./profiling/yololite_1_P_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_16_1.json cpu ./profiling/yololite_7_P_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_16_1.json gpu ./profiling/yololite_7_P_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_16.json cpu ./profiling/yololite_0_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_16.json gpu ./profiling/yololite_0_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_2.json cpu ./profiling/yololite_1_P_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_2.json gpu ./profiling/yololite_1_P_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_16_1.json cpu ./profiling/yololite_10_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_16_1.json gpu ./profiling/yololite_10_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json cpu ./profiling/yololite_9_P_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_1.json gpu ./profiling/yololite_9_P_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_8.json cpu ./profiling/yololite_9_P_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_8.json gpu ./profiling/yololite_9_P_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json cpu ./profiling/yololite_11_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_1.json gpu ./profiling/yololite_11_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_4_1.json cpu ./profiling/yololite_9_P_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_4_1.json gpu ./profiling/yololite_9_P_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_4_1.json cpu ./profiling/yololite_8_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_4_1.json gpu ./profiling/yololite_8_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_2_1.json cpu ./profiling/yololite_2_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_2_1.json gpu ./profiling/yololite_2_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json cpu ./profiling/yololite_4_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_1.json gpu ./profiling/yololite_4_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_4_1.json cpu ./profiling/yololite_2_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_4_1.json gpu ./profiling/yololite_2_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json cpu ./profiling/yololite_7_P_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_1.json gpu ./profiling/yololite_7_P_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_16.json cpu ./profiling/yololite_8_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_16.json gpu ./profiling/yololite_8_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_2_1.json cpu ./profiling/yololite_10_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_2_1.json gpu ./profiling/yololite_10_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_2_1.json cpu ./profiling/yololite_4_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_2_1.json gpu ./profiling/yololite_4_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_2_1.json cpu ./profiling/yololite_5_P_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_2_1.json gpu ./profiling/yololite_5_P_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_16.json cpu ./profiling/yololite_9_P_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_16.json gpu ./profiling/yololite_9_P_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_2.json cpu ./profiling/yololite_0_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_2.json gpu ./profiling/yololite_0_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_2_1.json cpu ./profiling/yololite_8_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_2_1.json gpu ./profiling/yololite_8_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_16_1.json cpu ./profiling/yololite_8_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_16_1.json gpu ./profiling/yololite_8_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_4.json cpu ./profiling/yololite_8_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_4.json gpu ./profiling/yololite_8_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_2.json cpu ./profiling/yololite_9_P_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_2.json gpu ./profiling/yololite_9_P_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_8.json cpu ./profiling/yololite_11_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_8.json gpu ./profiling/yololite_11_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_8_1.json cpu ./profiling/yololite_9_P_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_8_1.json gpu ./profiling/yololite_9_P_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_8.json cpu ./profiling/yololite_8_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_8.json gpu ./profiling/yololite_8_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_4.json cpu ./profiling/yololite_6_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_4.json gpu ./profiling/yololite_6_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_8_1.json cpu ./profiling/yololite_4_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_8_1.json gpu ./profiling/yololite_4_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_16.json cpu ./profiling/yololite_10_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_16.json gpu ./profiling/yololite_10_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_8.json cpu ./profiling/yololite_7_P_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_8.json gpu ./profiling/yololite_7_P_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_4_1.json cpu ./profiling/yololite_1_P_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_4_1.json gpu ./profiling/yololite_1_P_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_4_1.json cpu ./profiling/yololite_4_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_4_1.json gpu ./profiling/yololite_4_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_8_1.json cpu ./profiling/yololite_7_P_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_8_1.json gpu ./profiling/yololite_7_P_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json cpu ./profiling/yololite_8_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_1.json gpu ./profiling/yololite_8_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_16_1.json cpu ./profiling/yololite_2_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_16_1.json gpu ./profiling/yololite_2_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_2.json cpu ./profiling/yololite_7_P_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_2.json gpu ./profiling/yololite_7_P_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_16.json cpu ./profiling/yololite_1_P_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_1_16.json gpu ./profiling/yololite_1_P_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_4.json cpu ./profiling/yololite_7_P_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_4.json gpu ./profiling/yololite_7_P_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_2_1.json cpu ./profiling/yololite_3_P_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_2_1.json gpu ./profiling/yololite_3_P_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_16_1.json cpu ./profiling/yololite_11_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_16_1.json gpu ./profiling/yololite_11_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json cpu ./profiling/yololite_6_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_1.json gpu ./profiling/yololite_6_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_4_1.json cpu ./profiling/yololite_7_P_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_4_1.json gpu ./profiling/yololite_7_P_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_8_1.json cpu ./profiling/yololite_6_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_8_1.json gpu ./profiling/yololite_6_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_16_1.json cpu ./profiling/yololite_6_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_16_1.json gpu ./profiling/yololite_6_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_8.json cpu ./profiling/yololite_3_P_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_8.json gpu ./profiling/yololite_3_P_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_4_1.json cpu ./profiling/yololite_0_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_4_1.json gpu ./profiling/yololite_0_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_8.json cpu ./profiling/yololite_10_C_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_1_8.json gpu ./profiling/yololite_10_C_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_4.json cpu ./profiling/yololite_3_P_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_4.json gpu ./profiling/yololite_3_P_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_16_1.json cpu ./profiling/yololite_5_P_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_16_1.json gpu ./profiling/yololite_5_P_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_2.json cpu ./profiling/yololite_8_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_8_C_1_2.json gpu ./profiling/yololite_8_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json cpu ./profiling/yololite_0_C_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_1_1.json gpu ./profiling/yololite_0_C_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_8_1.json cpu ./profiling/yololite_1_P_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_1_P_8_1.json gpu ./profiling/yololite_1_P_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_4_1.json cpu ./profiling/yololite_11_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_4_1.json gpu ./profiling/yololite_11_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_16_1.json cpu ./profiling/yololite_0_C_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_16_1.json gpu ./profiling/yololite_0_C_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_2.json cpu ./profiling/yololite_6_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_2.json gpu ./profiling/yololite_6_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_8_1.json cpu ./profiling/yololite_0_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_0_C_8_1.json gpu ./profiling/yololite_0_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_2.json cpu ./profiling/yololite_3_P_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_2.json gpu ./profiling/yololite_3_P_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_16_1.json cpu ./profiling/yololite_9_P_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_16_1.json gpu ./profiling/yololite_9_P_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_4.json cpu ./profiling/yololite_5_P_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_4.json gpu ./profiling/yololite_5_P_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_4_1.json cpu ./profiling/yololite_5_P_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_4_1.json gpu ./profiling/yololite_5_P_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_2_1.json cpu ./profiling/yololite_6_C_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_2_1.json gpu ./profiling/yololite_6_C_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_16_1.json cpu ./profiling/yololite_3_P_16_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_16_1.json gpu ./profiling/yololite_3_P_16_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_8_1.json cpu ./profiling/yololite_11_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_8_1.json gpu ./profiling/yololite_11_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_16.json cpu ./profiling/yololite_7_P_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_1_16.json gpu ./profiling/yololite_7_P_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_8.json cpu ./profiling/yololite_5_P_1_8_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_8.json gpu ./profiling/yololite_5_P_1_8_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_16.json cpu ./profiling/yololite_6_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_6_C_1_16.json gpu ./profiling/yololite_6_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_2.json cpu ./profiling/yololite_2_C_1_2_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_1_2.json gpu ./profiling/yololite_2_C_1_2_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_4.json cpu ./profiling/yololite_9_P_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_1_4.json gpu ./profiling/yololite_9_P_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_2_1.json cpu ./profiling/yololite_9_P_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_9_P_2_1.json gpu ./profiling/yololite_9_P_2_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_16.json cpu ./profiling/yololite_5_P_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_5_P_1_16.json gpu ./profiling/yololite_5_P_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_16.json cpu ./profiling/yololite_11_C_1_16_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_11_C_1_16.json gpu ./profiling/yololite_11_C_1_16_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_4_1.json cpu ./profiling/yololite_10_C_4_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_10_C_4_1.json gpu ./profiling/yololite_10_C_4_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_4.json cpu ./profiling/yololite_4_C_1_4_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_4_C_1_4.json gpu ./profiling/yololite_4_C_1_4_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json cpu ./profiling/yololite_3_P_1_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_3_P_1_1.json gpu ./profiling/yololite_3_P_1_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_8_1.json cpu ./profiling/yololite_2_C_8_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_2_C_8_1.json gpu ./profiling/yololite_2_C_8_1_gpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_2_1.json cpu ./profiling/yololite_7_P_2_1_cpu.timing normal
sudo taskset -c 4-7 ./build/scheduling/execute_kernel/execute_kernel ./database/info/yololite_7_P_2_1.json gpu ./profiling/yololite_7_P_2_1_gpu.timing normal
